version: '3.5'


services: 

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    volumes: 
      - "./challenge:/var/app"
    working_dir: /var/app

  start:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    volumes: 
      - "./challenge:/var/app"
    working_dir: /var/app
    command: yarn start